server:
    port: 8888

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        # local db
        # url: jdbc:mariadb://localhost:3306/encore?useUnicode=true
        # username: root
        # password: 123456789

        # cloud
        url: jdbc:mariadb://localhost:6033/encore?useUnicode=true
        # username: root
        # password: 123456789
        # 아래처럼 줘도 되고 위처럼 줘도 된다.
        username: work_user
        password: work_password

mybatis:
    mapper-locations: mappers/*.xml